# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-08 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(max_length=16),
        ),
    ]
