# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-02 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '\u8d44\u4ea7\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u4e1a\u52a1\u7ebf')),
            ],
            options={
                'verbose_name_plural': '\u4e1a\u52a1\u7ebf\u8868',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=8, verbose_name='\u63d2\u69fd\u4f4d')),
                ('model', models.CharField(max_length=32, verbose_name='\u78c1\u76d8\u578b\u53f7')),
                ('capacity', models.FloatField(verbose_name='\u78c1\u76d8\u5bb9\u91cfGB')),
                ('pd_type', models.CharField(max_length=32, verbose_name='\u78c1\u76d8\u7c7b\u578b')),
            ],
            options={
                'verbose_name_plural': '\u786c\u76d8\u8868',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '\u9519\u8bef\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u673a\u623f')),
                ('floor', models.IntegerField(default=1, verbose_name='\u697c\u5c42')),
            ],
            options={
                'verbose_name_plural': '\u673a\u623f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=32, verbose_name='\u63d2\u69fd\u4f4d')),
                ('manufacturer', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(max_length=64, verbose_name='\u578b\u53f7')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='\u5bb9\u91cf')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5185\u5b58SN\u53f7')),
                ('speed', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u901f\u5ea6')),
            ],
            options={
                'verbose_name_plural': '\u5185\u5b58\u8868',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u7f51\u5361\u540d\u79f0')),
                ('hwaddr', models.CharField(max_length=64, verbose_name='\u7f51\u5361mac\u5730\u5740')),
                ('netmask', models.CharField(max_length=64)),
                ('ipaddrs', models.CharField(max_length=256, verbose_name='ip\u5730\u5740')),
                ('up', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '\u7f51\u5361\u8868',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_status_id', models.IntegerField(choices=[(1, '\u4e0a\u67b6'), (4, '\u4e0b\u67b6'), (2, '\u5728\u7ebf'), (3, '\u79bb\u7ebf')], default=1)),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('os_platform', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u7cfb\u7edf')),
                ('os_version', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('sn', models.CharField(db_index=True, max_length=64, verbose_name='SN\u53f7')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u578b\u53f7')),
                ('cpu_count', models.IntegerField(blank=True, null=True, verbose_name='CPU\u4e2a\u6570')),
                ('cpu_physical_count', models.IntegerField(blank=True, null=True, verbose_name='CPU\u7269\u7406\u4e2a\u6570')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU\u578b\u53f7')),
                ('latest_date', models.DateField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BusinessUnit', verbose_name='\u5c5e\u4e8e\u7684\u4e1a\u52a1\u7ebf')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.IDC', verbose_name='IDC\u673a\u623f')),
            ],
            options={
                'verbose_name_plural': '\u670d\u52a1\u5668\u8868',
            },
        ),
        migrations.AddField(
            model_name='nic',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic_list', to='api.Server'),
        ),
        migrations.AddField(
            model_name='memory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_list', to='api.Server'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Server'),
        ),
        migrations.AddField(
            model_name='disk',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_list', to='api.Server', verbose_name='\u670d\u52a1\u5668'),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='api.Server'),
        ),
    ]
