# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-03 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200102_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.CharField(max_length=8, verbose_name='\u78c1\u76d8\u5bb9\u91cfGB'),
        ),
    ]
